### ISSUE TITLE
cep unico

### ISSUE THREAD

**Issue by Squifordl** [dudu15051505/mapa-claro-beta#1]
já pelo nome ja se diz, cidades que possuem ceps unicos puxa a cidade em geral

**Comment by dudu15051505** [comment]
> já pelo nome ja se diz, cidades que possuem ceps unicos puxa a cidade em geral

então, não tenho muita ideia de como arrumar isso, se é que tem como.
pq a cidades que a vários locais com cep único, e isso é por conta do correios.

tanto no serviço [viacep.com.br/](https://viacep.com.br/) quando e principalmente a base api própria da claro, nessas cidades que possuem cep único, retornam uma informação genérica na consulta.

com isso, só posso aceitar ideias de como solucionar ou contornar essa situação.

**Comment by Squifordl** [comment]
Pensei sobre utilizar API do MAPS com o nome da rua, porém pelo que vi a API de viabilidade é somente por cep, ai é um problema

**Comment by dudu15051505** [comment]
> Pensei sobre utilizar API do MAPS com o nome da rua, porém pelo que vi a API de viabilidade é somente por cep, ai é um problema

sim, as duas apis que estão expostas no site da claro só realizam a consulta com base no cep ou nome da cidade.
isso limita muito as opções do que pode ser feito pra tratar melhor esse caso de cep único.
